'use client';

import { FormEvent, useState, useTransition } from 'react';
import { useRouter } from 'next/navigation';
import { saveManagedPolicy } from '@/features/admin/actions';

export type PolicyEditorValue = { id?: string; cityId: string | null; title: string; category: string; summary: string; interpretation: string; keyPoints: string[]; issuingAuthority: string; documentNumber: string | null; sourceName: string; sourceUrl: string; revisionNote: string | null; supersededAt: Date | null; publishedAt: Date; effectiveAt: Date | null; status: 'draft' | 'pending' | 'published' | 'hidden' | 'deleted' };
const empty: PolicyEditorValue = { cityId: null, title: '', category: '', summary: '', interpretation: '', keyPoints: [], issuingAuthority: '', documentNumber: null, sourceName: '', sourceUrl: '', revisionNote: null, supersededAt: null, publishedAt: new Date(), effectiveAt: null, status: 'draft' };
const dateValue = (value: Date | null) => value ? value.toISOString().slice(0, 10) : '';

export function PolicyEditor({ value = empty, cities }: { value?: PolicyEditorValue; cities: Array<{ id: string; name: string }> }) {
  const [open, setOpen] = useState(!value.id); const [message, setMessage] = useState(''); const [pending, startTransition] = useTransition(); const router = useRouter();
  if (!open) return <button onClick={() => setOpen(true)}>编辑</button>;
  return <form className="managed-content-form" onSubmit={(event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const data = new FormData(event.currentTarget); startTransition(async () => { const result = await saveManagedPolicy({ id: value.id, cityId: data.get('cityId'), title: data.get('title'), category: data.get('category'), summary: data.get('summary'), interpretation: data.get('interpretation'), keyPoints: String(data.get('keyPoints') ?? '').split('\n').map((item) => item.trim()).filter(Boolean), issuingAuthority: data.get('issuingAuthority'), documentNumber: data.get('documentNumber'), sourceName: data.get('sourceName'), sourceUrl: data.get('sourceUrl'), publishedAt: data.get('publishedAt'), effectiveAt: data.get('effectiveAt') || undefined, revisionNote: data.get('revisionNote'), status: data.get('status'), superseded: data.get('superseded') === 'on' }); setMessage(result.ok ? '政策已保存' : result.message); if (result.ok) { setOpen(false); router.refresh(); } }); }}><select name="cityId" defaultValue={value.cityId ?? ''}><option value="">全国</option>{cities.map((city) => <option value={city.id} key={city.id}>{city.name}</option>)}</select><input name="title" defaultValue={value.title} placeholder="政策标题" required /><input name="category" defaultValue={value.category} placeholder="分类" required /><textarea name="summary" defaultValue={value.summary} placeholder="政策摘要" required /><textarea name="interpretation" defaultValue={value.interpretation} placeholder="平台解读" required /><textarea name="keyPoints" defaultValue={value.keyPoints.join('\n')} placeholder="重点，每行一条" required /><input name="issuingAuthority" defaultValue={value.issuingAuthority} placeholder="发布机关" required /><input name="documentNumber" defaultValue={value.documentNumber ?? ''} placeholder="文号" /><input name="sourceName" defaultValue={value.sourceName} placeholder="官方来源名称" required /><input name="sourceUrl" type="url" defaultValue={value.sourceUrl} placeholder="https://*.gov.cn" required /><label>发布日期<input name="publishedAt" type="date" defaultValue={dateValue(value.publishedAt)} required /></label><label>实施日期<input name="effectiveAt" type="date" defaultValue={dateValue(value.effectiveAt)} /></label><textarea name="revisionNote" defaultValue={value.revisionNote ?? ''} placeholder="修订或失效说明" /><select name="status" defaultValue={value.status}><option value="draft">草稿</option><option value="pending">待审核</option><option value="published">发布</option><option value="hidden">隐藏</option><option value="deleted">删除</option></select><label><input name="superseded" type="checkbox" defaultChecked={Boolean(value.supersededAt)} /> 标记为已废止/被替代</label><button disabled={pending}>{pending ? '保存中…' : '保存政策'}</button>{value.id ? <button type="button" onClick={() => setOpen(false)}>取消</button> : null}<small role="status">{message}</small></form>;
}
